# fly.toml app configuration file generated for solvify-back on 2023-08-28T19:39:41-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "solvify-back"
primary_region = "gig"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  MONGODB_URI = ${{ secrets.MONGODB_URI }}
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
